language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - pip install -U -r requirements.test.txt --use-mirrors
  - pip install .

script:
  - coverage run --source=dehydrate setup.py test
  - coverage report -m

after_script:
  - coveralls --verbose
